#define N_TITLE_LETTER  6u
#define N_TITLE_LETTERS 8u
#define N_TITLE         (N_TITLE_LETTER * N_TITLE_LETTERS)

#define OFFSET_TITLE_S 0u
#define OFFSET_TITLE_O (OFFSET_TITLE_S + N_TITLE_LETTER)
#define OFFSET_TITLE_L (OFFSET_TITLE_O + N_TITLE_LETTER)
#define OFFSET_TITLE_I (OFFSET_TITLE_L + N_TITLE_LETTER)
#define OFFSET_TITLE_T (OFFSET_TITLE_I + N_TITLE_LETTER)
#define OFFSET_TITLE_A (OFFSET_TITLE_T + N_TITLE_LETTER)
#define OFFSET_TITLE_R (OFFSET_TITLE_A + N_TITLE_LETTER)
#define OFFSET_TITLE_E (OFFSET_TITLE_R + N_TITLE_LETTER)

extern const unsigned char title_textures[];
